FROM golang:1.21-alpine as builder

WORKDIR /app

COPY main.go main.go

RUN go mod init example.com/gorilla && go get -u github.com/gorilla/mux

RUN go build -o main

FROM alpine:3.20 as base

WORKDIR /app

RUN addgroup -S goweb && adduser -S goweb -G goweb

USER goweb

COPY --from=builder /app/main .

EXPOSE 8080

CMD [ "./main" ]