version: "3.9"

services:
  app:
    scale: 2 
    build:
      context: .
      dockerfile: Dockerfile
    command: go run main.go
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: always
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=mydb
      - DB_PORT=5432
    networks:
      - backend

  db:
    image: postgres:14.5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    restart: always
    networks:
      - backend

networks:
  backend:
    driver: bridge